[project]
name = "ml-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.2",
    "pip>=25.2",
    "polars>=1.32.3",
    "seaborn>=0.13.2",
]
